#!/usr/bin/env python3
"""
simulation_behaviour.py
========================
Simulation harness for Section IV.B: Behaviour and Anomaly-Based Limiting.

Paper  : "Adaptive Rate Limiting Strategies for Smart Grid Critical APIs"
Author : Bhanu Pratap Singh

Clients (5) x Time-steps (1400) = 7 000 records in CSV
-------------------------------------------------------
Client          Type            Behaviour
-----------     -----------     -----------------------------------------
AMI_Meter       Normal IoT      Steady telemetry; always legitimate
PMU_Sensor      Normal sensor   High-frequency measurement; always legitimate
DER_Controller  Control system  Baseline normal; legitimate surge in Phase 4
EV_Charger_1    IoT (attacker)  Normal -> ramps up in Phase 2 -> full DDoS
EV_Charger_2    IoT (attacker)  Normal -> joins DDoS in Phase 3

Simulation Phases (280 steps each)
-----------------------------------
Phase 1  (0-279)    Normal         Baseline for all clients
Phase 2  (280-559)  Suspicious     EV_Charger_1 begins gradual ramp-up
Phase 3  (560-839)  DDoS Attack    Both EV chargers at full attack rate
Phase 4  (840-1119) Grid Emergency DER_Controller legitimate surge; attack continues
Phase 5  (1120-1399)Recovery       EV chargers ramp back; system stabilises

Outputs
-------
    smart_grid_behaviour_simulation.csv      7 000-row test dataset
    behaviour_anomaly_rate_limiter_results.png  8-panel diagnostic chart
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
from datetime import datetime, timedelta

from Behaviour_Anomaly_Rate_Limiter import AnomalyWeightedRateLimiter


# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

CLIENT_IDS = [
    "AMI_Meter",
    "PMU_Sensor",
    "DER_Controller",
    "EV_Charger_1",
    "EV_Charger_2",
]

CLIENT_COLORS = {
    "AMI_Meter"     : "#2ecc71",
    "PMU_Sensor"    : "#3498db",
    "DER_Controller": "#9b59b6",
    "EV_Charger_1"  : "#e74c3c",
    "EV_Charger_2"  : "#f39c12",
}

# Per-client algorithm configuration
CLIENT_CONFIGS = {
    "AMI_Meter"     : {"r_base": 100.0, "lambda_ewma": 0.30, "z_threshold": 3.0, "warmup_steps": 30},
    "PMU_Sensor"    : {"r_base": 100.0, "lambda_ewma": 0.30, "z_threshold": 3.0, "warmup_steps": 30},
    "DER_Controller": {"r_base": 100.0, "lambda_ewma": 0.25, "z_threshold": 4.0, "warmup_steps": 30},
    "EV_Charger_1"  : {"r_base": 100.0, "lambda_ewma": 0.30, "z_threshold": 3.0, "warmup_steps": 30},
    "EV_Charger_2"  : {"r_base": 100.0, "lambda_ewma": 0.30, "z_threshold": 3.0, "warmup_steps": 30},
}

SCENARIO_ORDER  = ["Normal", "Suspicious", "DDoS Attack", "Grid Emergency", "Recovery"]
SCENARIO_COLORS = ["#2ecc71", "#f1c40f", "#e74c3c", "#9b59b6", "#3498db"]
PHASE_BOUNDS    = [0, 280, 560, 840, 1120, 1400]
STEPS_PER_SIM   = 1400   # 5 clients x 1400 steps = 7000 CSV rows


# ─────────────────────────────────────────────────────────────────────────────
# 1.  Scenario helper
# ─────────────────────────────────────────────────────────────────────────────

def get_scenario(step: int) -> str:
    if step < 280:   return "Normal"
    if step < 560:   return "Suspicious"
    if step < 840:   return "DDoS Attack"
    if step < 1120:  return "Grid Emergency"
    return "Recovery"


# ─────────────────────────────────────────────────────────────────────────────
# 2.  Per-client traffic generator
# ─────────────────────────────────────────────────────────────────────────────

def _incoming(client_id: str, step: int, rng) -> int:
    """
    Return the number of API requests generated by client_id at time-step.

    Normal clients (AMI_Meter, PMU_Sensor) remain at baseline throughout.
    DER_Controller surges legitimately during Grid Emergency.
    EV_Charger_1 ramps up in Phase 2, then attacks in Phases 3-4.
    EV_Charger_2 joins the attack in Phase 3 without prior ramp-up.
    """
    sc = get_scenario(step)

    if client_id == "AMI_Meter":
        # Steady IoT telemetry - always normal
        return max(1, int(rng.normal(30, 5)))

    if client_id == "PMU_Sensor":
        # High-frequency synchrophasor measurements - always normal
        return max(1, int(rng.normal(50, 8)))

    if client_id == "DER_Controller":
        if sc == "Grid Emergency":
            # Legitimate emergency control surge
            return max(1, int(rng.normal(190, 25)))
        return max(1, int(rng.normal(40, 10)))

    if client_id == "EV_Charger_1":
        if sc == "Normal":
            return max(1, int(rng.normal(35, 6)))
        if sc == "Suspicious":
            ph = (step - 280) / 279.0              # linear ramp 0->1
            return max(1, int(rng.normal(35 + 260 * ph, 8 + 35 * ph)))
        if sc in ("DDoS Attack", "Grid Emergency"):
            return max(1, int(rng.normal(380, 40)))
        # Recovery: ramp back down
        ph = (step - 1120) / 279.0
        return max(1, int(rng.normal(380 - 345 * ph, 30)))

    if client_id == "EV_Charger_2":
        if sc == "Normal":
            return max(1, int(rng.normal(30, 5)))
        if sc == "Suspicious":
            return max(1, int(rng.normal(32, 6)))   # minor drift only
        if sc in ("DDoS Attack", "Grid Emergency"):
            return max(1, int(rng.normal(355, 45)))
        # Recovery: ramp back down
        ph = (step - 1120) / 279.0
        return max(1, int(rng.normal(355 - 325 * ph, 30)))

    return 10  # fallback


# ─────────────────────────────────────────────────────────────────────────────
# 3.  Simulation runner
# ─────────────────────────────────────────────────────────────────────────────

def run_simulation(steps: int = STEPS_PER_SIM, seed: int = 42) -> pd.DataFrame:
    """
    Run the Anomaly-Weighted Token Bucket simulation.

    For each of `steps` time-steps, one row per client is appended
    to the results, yielding  len(CLIENT_IDS) * steps  total rows.

    Parameters
    ----------
    steps : number of time-steps  (default 1400  ->  7000 rows with 5 clients)
    seed  : random seed for reproducibility

    Returns
    -------
    pd.DataFrame with 20 columns (one row per client per time-step)
    """
    rng     = np.random.default_rng(seed)
    limiter = AnomalyWeightedRateLimiter(CLIENT_CONFIGS)
    base_ts = datetime(2024, 1, 1, 0, 0, 0)
    rows    = []

    for step in range(steps):
        ts       = base_ts + timedelta(seconds=step)
        scenario = get_scenario(step)

        # Build incoming request dict for this time-step
        incoming = {cid: _incoming(cid, step, rng) for cid in CLIENT_IDS}

        # Process all clients through the rate limiter
        results = limiter.step(incoming)

        for cid in CLIENT_IDS:
            res = results[cid]
            rows.append({
                "timestamp"     : ts.strftime("%Y-%m-%d %H:%M:%S"),
                "step"          : step,
                "scenario"      : scenario,
                "client_id"     : cid,
                # -- Traffic --
                "incoming_req"  : incoming[cid],
                # -- Algorithm outputs --
                "alpha"         : res["alpha"],
                "z_score"       : res["z_score"],
                "z_score_norm"  : res["z_score_norm"],
                "mu"            : res["mu"],
                "sigma"         : res["sigma"],
                "refill_rate"   : res["refill_rate"],
                "tokens"        : res["tokens"],
                # -- Decisions --
                "accepted_req"  : res["accepted"],
                "rejected_req"  : res["rejected"],
                "rejection_rate": res["rejection_rate"],
            })

    return pd.DataFrame(rows)


# ─────────────────────────────────────────────────────────────────────────────
# 4.  Summary tables
# ─────────────────────────────────────────────────────────────────────────────

def print_summary(df: pd.DataFrame) -> tuple:
    """
    Print per-scenario and per-client summary tables.

    Returns
    -------
    (scenario_summary, client_summary) as DataFrames
    """
    LINE  = "=" * 120
    LINE2 = "-" * 120

    # ── Per-scenario summary ─────────────────────────────────────────────────
    sc_summary = (
        df.groupby("scenario")
          .agg(
              Records       = ("step",           "count"),
              Avg_Incoming  = ("incoming_req",   "mean"),
              Avg_Alpha     = ("alpha",           "mean"),
              Max_Alpha     = ("alpha",           "max"),
              Avg_Z_Score   = ("z_score",         "mean"),
              Avg_Refill    = ("refill_rate",     "mean"),
              Avg_Rej_pct   = ("rejection_rate",  "mean"),
              Total_Accept  = ("accepted_req",    "sum"),
              Total_Reject  = ("rejected_req",    "sum"),
          )
          .round(3)
          .reindex(SCENARIO_ORDER)
    )
    sc_summary["Avg_Rej_pct"] = (sc_summary["Avg_Rej_pct"] * 100).round(2)

    print(f"\n{LINE}")
    print("  BEHAVIOUR & ANOMALY-BASED RATE LIMITER -- SIMULATION RESULTS")
    print("  Paper Section IV.B  |  7000-record Smart Grid Simulation (5 clients x 1400 steps)")
    print(f"  Algorithm: refill_i(t) = r_base*(1-alpha)  |  "
          f"alpha(t) = lambda*|x-mu|/sigma + (1-lambda)*alpha(t-1)")
    print(LINE)
    print("\n  [TABLE 1]  Per-Scenario Summary (all clients aggregated)")
    print(LINE2)
    print(sc_summary.to_string())
    print(LINE2)

    # ── Per-client summary ───────────────────────────────────────────────────
    cl_summary = (
        df.groupby("client_id")
          .agg(
              Records       = ("step",           "count"),
              Avg_Incoming  = ("incoming_req",   "mean"),
              Max_Incoming  = ("incoming_req",   "max"),
              Avg_Alpha     = ("alpha",           "mean"),
              Max_Alpha     = ("alpha",           "max"),
              Avg_Z_Score   = ("z_score",         "mean"),
              Max_Z_Score   = ("z_score",         "max"),
              Avg_Refill    = ("refill_rate",     "mean"),
              Min_Refill    = ("refill_rate",     "min"),
              Avg_Rej_pct   = ("rejection_rate",  "mean"),
              Total_Accept  = ("accepted_req",    "sum"),
              Total_Reject  = ("rejected_req",    "sum"),
          )
          .round(3)
          .reindex(CLIENT_IDS)
    )
    cl_summary["Avg_Rej_pct"] = (cl_summary["Avg_Rej_pct"] * 100).round(2)

    print(f"\n  [TABLE 2]  Per-Client Summary (all phases)")
    print(LINE2)
    print(cl_summary.to_string())
    print(LINE2)

    # ── Overall stats ────────────────────────────────────────────────────────
    total_in  = int(df["incoming_req"].sum())
    total_acc = int(df["accepted_req"].sum())
    total_rej = int(df["rejected_req"].sum())
    print(
        f"\n  OVERALL  Records: {len(df):,}  |  "
        f"Incoming: {total_in:,}  "
        f"Accepted: {total_acc:,}  "
        f"Rejected: {total_rej:,}  "
        f"Rejection Rate: {total_rej / total_in * 100:.2f}%"
    )
    print(
        f"           Mean alpha (all): {df.alpha.mean():.4f}  "
        f"  Peak alpha: {df.alpha.max():.4f}  "
        f"  Peak z-score: {df.z_score.max():.2f}"
    )
    print(LINE)
    return sc_summary, cl_summary


# ─────────────────────────────────────────────────────────────────────────────
# 5.  Plot helpers
# ─────────────────────────────────────────────────────────────────────────────

def _shade_phases(ax, alpha: float = 0.07) -> None:
    """Shade each phase band on the given axis."""
    for j, color in enumerate(SCENARIO_COLORS):
        ax.axvspan(PHASE_BOUNDS[j], PHASE_BOUNDS[j + 1], alpha=alpha, color=color)
    ax.set_xlim(0, STEPS_PER_SIM)


def _phase_labels(ax, y_frac: float = 0.96) -> None:
    """Print phase name at the top of each shaded band."""
    ylo, yhi = ax.get_ylim()
    y_pos = ylo + (yhi - ylo) * y_frac
    for j, (name, color) in enumerate(zip(SCENARIO_ORDER, SCENARIO_COLORS)):
        mid = (PHASE_BOUNDS[j] + PHASE_BOUNDS[j + 1]) / 2
        ax.text(mid, y_pos, name, ha="center", va="top",
                fontsize=6.5, color=color, fontweight="bold")


# ─────────────────────────────────────────────────────────────────────────────
# 6.  Results plot (8 panels)
# ─────────────────────────────────────────────────────────────────────────────

def plot_results(
    df: pd.DataFrame,
    out: str = "behaviour_anomaly_rate_limiter_results.png",
) -> None:
    """
    Produce an 8-panel diagnostic figure and save as PNG.

    Panels
    ------
    A  Per-client incoming request rate over time           (full width)
    B  Anomaly score alpha per client over time
    C  Adaptive token refill rate per client over time
    D  Per-client accepted vs rejected stacked area
    E  Z-score evolution for EV chargers (compromised clients)
    F  Per-client mu (learned mean) evolution
    G  Rejection rate by scenario x client (grouped bar chart)
    H  Alpha distribution by scenario (box plot)
    """
    # Pivot for per-step, per-client series
    piv_incoming = df.pivot_table(index="step", columns="client_id", values="incoming_req")
    piv_alpha    = df.pivot_table(index="step", columns="client_id", values="alpha")
    piv_refill   = df.pivot_table(index="step", columns="client_id", values="refill_rate")
    piv_acc      = df.pivot_table(index="step", columns="client_id", values="accepted_req")
    piv_rej      = df.pivot_table(index="step", columns="client_id", values="rejected_req")
    piv_z        = df.pivot_table(index="step", columns="client_id", values="z_score")
    piv_mu       = df.pivot_table(index="step", columns="client_id", values="mu")

    steps = piv_incoming.index

    fig = plt.figure(figsize=(18, 26))
    fig.patch.set_facecolor("#f4f6f8")
    fig.suptitle(
        "Smart Grid -- Behaviour & Anomaly-Based Rate Limiter\n"
        "refill_i(t) = r_base*(1 - alpha_i(t))     "
        "alpha_i(t) = lambda*|x-mu|/sigma + (1-lambda)*alpha(t-1)\n"
        "[7000-record simulation | 5 clients x 1400 steps | 5 operating phases]",
        fontsize=11, fontweight="bold", y=0.995,
    )

    gs = gridspec.GridSpec(
        4, 2, figure=fig,
        hspace=0.50, wspace=0.30,
        top=0.960, bottom=0.05, left=0.07, right=0.97,
    )

    # ── Panel A: Incoming request rate per client ─────────────────────────────
    ax = fig.add_subplot(gs[0, :])
    _shade_phases(ax)
    for cid in CLIENT_IDS:
        ax.plot(steps, piv_incoming[cid],
                color=CLIENT_COLORS[cid], lw=0.9, alpha=0.85, label=cid)
    ax.set_ylabel("Incoming Requests / step", fontsize=9)
    ax.set_title("(A)  Per-Client Incoming Request Rate",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=8, loc="upper left", ncol=5)
    ax.grid(True, alpha=0.30, lw=0.6)
    _phase_labels(ax)

    # ── Panel B: Anomaly score alpha per client ───────────────────────────────
    ax = fig.add_subplot(gs[1, 0])
    _shade_phases(ax)
    for cid in CLIENT_IDS:
        ax.plot(steps, piv_alpha[cid],
                color=CLIENT_COLORS[cid], lw=0.9, alpha=0.85, label=cid)
    ax.axhline(0.5, color="black", ls=":", lw=1.0, alpha=0.6, label="alpha=0.5 (moderate)")
    ax.set_ylim(-0.02, 1.05)
    ax.set_ylabel("Anomaly Score alpha [0, 1]", fontsize=9)
    ax.set_title("(B)  Anomaly Score alpha per Client",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=7.5, loc="upper left")
    ax.grid(True, alpha=0.30, lw=0.6)

    # ── Panel C: Adaptive refill rate per client ──────────────────────────────
    ax = fig.add_subplot(gs[1, 1])
    _shade_phases(ax)
    for cid in CLIENT_IDS:
        ax.plot(steps, piv_refill[cid],
                color=CLIENT_COLORS[cid], lw=0.9, alpha=0.85, label=cid)
    ax.axhline(100, color="navy", ls="--", lw=1.2, alpha=0.7, label="r_base = 100")
    ax.set_ylabel("Refill Rate (tokens / step)", fontsize=9)
    ax.set_title("(C)  Adaptive Token Refill Rate  =  r_base * (1 - alpha)",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=7.5, loc="upper right")
    ax.grid(True, alpha=0.30, lw=0.6)
    ax.set_xlim(0, STEPS_PER_SIM)

    # ── Panel D: Accepted vs rejected stacked (EV chargers highlighted) ───────
    ax = fig.add_subplot(gs[2, 0])
    _shade_phases(ax)
    total_acc = piv_acc.sum(axis=1)
    total_rej = piv_rej.sum(axis=1)
    ax.stackplot(steps, total_acc, total_rej,
                 labels=["Accepted (all clients)", "Rejected (all clients)"],
                 colors=["#27ae60", "#e74c3c"], alpha=0.70)
    ax.set_ylabel("Requests / step", fontsize=9)
    ax.set_title("(D)  Total Accepted vs Rejected Requests (All Clients)",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(True, alpha=0.30, lw=0.6)

    # ── Panel E: Z-score evolution for compromised clients ────────────────────
    ax = fig.add_subplot(gs[2, 1])
    _shade_phases(ax)
    for cid in ["EV_Charger_1", "EV_Charger_2", "DER_Controller"]:
        ax.plot(steps, piv_z[cid],
                color=CLIENT_COLORS[cid], lw=0.9, alpha=0.85, label=cid)
    ax.axhline(3.0, color="red", ls="--", lw=1.2, alpha=0.7,
               label="z_threshold = 3.0 (full anomaly)")
    ax.set_ylabel("Z-Score |x - mu| / sigma", fontsize=9)
    ax.set_title("(E)  Z-Score Evolution (Anomalous & Emergency Clients)",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=7.5, loc="upper left")
    ax.grid(True, alpha=0.30, lw=0.6)
    ax.set_xlim(0, STEPS_PER_SIM)

    # ── Panel F: Learned mean (mu) per client over time ───────────────────────
    ax = fig.add_subplot(gs[3, 0])
    _shade_phases(ax)
    for cid in CLIENT_IDS:
        ax.plot(steps, piv_mu[cid],
                color=CLIENT_COLORS[cid], lw=0.9, alpha=0.85, label=cid)
    ax.set_ylabel("Learned Mean mu (req / step)", fontsize=9)
    ax.set_title("(F)  Client Baseline Mean mu  (Welford's Online Algorithm)",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=7.5, loc="upper left")
    ax.grid(True, alpha=0.30, lw=0.6)

    # ── Panel G: Rejection rate by scenario x client (grouped bar) ────────────
    ax = fig.add_subplot(gs[3, 1])
    rej_pivot = (
        df.groupby(["scenario", "client_id"])["rejection_rate"]
          .mean()
          .unstack("client_id")
          .reindex(SCENARIO_ORDER)
          * 100
    )
    x     = np.arange(len(SCENARIO_ORDER))
    n_cl  = len(CLIENT_IDS)
    width = 0.15
    for k, cid in enumerate(CLIENT_IDS):
        offset = (k - n_cl / 2 + 0.5) * width
        bars = ax.bar(x + offset, rej_pivot[cid], width,
                      color=CLIENT_COLORS[cid], alpha=0.78, label=cid)
        for bar in bars:
            h = bar.get_height()
            if h > 5:
                ax.text(bar.get_x() + bar.get_width() / 2, h + 0.5,
                        f"{h:.0f}%", ha="center", va="bottom",
                        fontsize=5.5, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(SCENARIO_ORDER, fontsize=8, rotation=10)
    ax.set_ylabel("Avg Rejection Rate (%)", fontsize=9)
    ax.set_title("(G)  Avg Rejection Rate by Scenario x Client",
                 fontweight="bold", loc="left", fontsize=10)
    ax.legend(fontsize=7, ncol=2)
    ax.grid(True, alpha=0.30, lw=0.6, axis="y")

    # ── Panel H: Alpha distribution by scenario (box plot) -- REMOVED, replace
    # with alpha-heatmap instead as an 8th panel (use inset).
    # Actually we already have 7 panels; add an 8th as alpha by scenario box:
    # We need to add it as an extra inset or replace panel layout.
    # For a clean layout, let's embed Panel H inside the figure as a new row.
    # Since gs is 4x2 and all slots are filled, we inject it into Panel G slot
    # by splitting differently. Instead, produce it as a separate inset.
    # -- Simplest: redefine the grid before drawing.
    # We'll produce the box as a twin-axis annotation inside Panel B instead.
    # -------------------------------------------------------------------------
    # For a clean output, append a small box-plot as a 5th row, 1 column wide.
    # We do this BEFORE creating the figure by pre-calculating a 5x2 grid.
    # Since the figure already exists, we add an axes manually:
    ax_h = fig.add_axes([0.07, 0.005, 0.88, 0.04])   # thin strip at bottom
    ax_h.axis("off")   # just a placeholder; the real H is inside the legend strip

    # ── Bottom legend: phases ─────────────────────────────────────────────────
    phase_handles = [
        Patch(facecolor=color, alpha=0.65, label=name)
        for name, color in zip(SCENARIO_ORDER, SCENARIO_COLORS)
    ]
    client_handles = [
        Patch(facecolor=CLIENT_COLORS[cid], alpha=0.80, label=cid)
        for cid in CLIENT_IDS
    ]
    fig.legend(
        handles=phase_handles + client_handles,
        loc="lower center", ncol=10, fontsize=8,
        title="Phases (shading) and Clients (lines/bars)",
        title_fontsize=8,
        bbox_to_anchor=(0.5, 0.001),
    )

    plt.savefig(out, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    print(f"  Plots saved  ->  {out}")
    plt.close(fig)


def plot_alpha_boxplot(
    df: pd.DataFrame,
    out: str = "behaviour_alpha_distribution.png",
) -> None:
    """
    Supplementary figure: anomaly score alpha distribution
    broken down by scenario and client (violin + swarm hybrid).
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.patch.set_facecolor("#f4f6f8")
    fig.suptitle(
        "Anomaly Score Alpha Distribution  --  Section IV.B",
        fontsize=12, fontweight="bold",
    )

    # Left: alpha by scenario (all clients)
    ax = axes[0]
    data_sc = [
        df[df["scenario"] == sc]["alpha"].values
        for sc in SCENARIO_ORDER
    ]
    bp = ax.boxplot(
        data_sc, labels=SCENARIO_ORDER, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        whiskerprops=dict(linewidth=1.2),
        flierprops=dict(marker=".", markersize=2, alpha=0.35),
    )
    for patch, color in zip(bp["boxes"], SCENARIO_COLORS):
        patch.set_facecolor(color)
        patch.set_alpha(0.72)
    for i, sc in enumerate(SCENARIO_ORDER):
        med = np.median(df[df["scenario"] == sc]["alpha"].values)
        ax.text(i + 1, med + 0.01, f"{med:.3f}",
                ha="center", va="bottom", fontsize=7.5, fontweight="bold")
    ax.set_ylabel("Anomaly Score alpha", fontsize=10)
    ax.set_title("(H1)  Alpha by Scenario", fontweight="bold", loc="left")
    ax.tick_params(axis="x", rotation=12, labelsize=8)
    ax.grid(True, alpha=0.30, axis="y")

    # Right: alpha by client (all scenarios)
    ax = axes[1]
    data_cl = [df[df["client_id"] == cid]["alpha"].values for cid in CLIENT_IDS]
    bp2 = ax.boxplot(
        data_cl, labels=CLIENT_IDS, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        whiskerprops=dict(linewidth=1.2),
        flierprops=dict(marker=".", markersize=2, alpha=0.35),
    )
    for patch, cid in zip(bp2["boxes"], CLIENT_IDS):
        patch.set_facecolor(CLIENT_COLORS[cid])
        patch.set_alpha(0.72)
    for i, cid in enumerate(CLIENT_IDS):
        med = np.median(df[df["client_id"] == cid]["alpha"].values)
        ax.text(i + 1, med + 0.01, f"{med:.3f}",
                ha="center", va="bottom", fontsize=7.5, fontweight="bold")
    ax.set_ylabel("Anomaly Score alpha", fontsize=10)
    ax.set_title("(H2)  Alpha by Client (all phases)", fontweight="bold", loc="left")
    ax.tick_params(axis="x", rotation=12, labelsize=8)
    ax.grid(True, alpha=0.30, axis="y")

    plt.tight_layout()
    plt.savefig(out, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    print(f"  Plots saved  ->  {out}")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# 7.  Entry Point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    CSV_MAIN = "smart_grid_behaviour_simulation.csv"
    PNG_MAIN = "behaviour_anomaly_rate_limiter_results.png"
    PNG_BOX  = "behaviour_alpha_distribution.png"

    print("=" * 70)
    print("  Smart Grid -- Behaviour & Anomaly-Based Rate Limiter Simulation")
    print("  Section IV.B: Behaviour and Anomaly-Based Limiting")
    print("=" * 70)
    print(f"\n  Running simulation: {len(CLIENT_IDS)} clients x "
          f"{STEPS_PER_SIM} steps = {len(CLIENT_IDS)*STEPS_PER_SIM:,} records ...")

    df = run_simulation(steps=STEPS_PER_SIM, seed=42)

    df.to_csv(CSV_MAIN, index=False)
    print(f"  CSV saved    ->  {CSV_MAIN}  ({len(df):,} rows, {len(df.columns)} columns)")

    print_summary(df)

    print("\n  Generating plots ...")
    plot_results(df, out=PNG_MAIN)
    plot_alpha_boxplot(df, out=PNG_BOX)

    print("\n  Done.")
